'use client'

import { useState } from 'react'
import { Activity, AlertTriangle, BarChart3, CheckCircle2, ChevronRight, ClipboardCheck, Database, FileCheck2, FileSearch, Files, Fingerprint, Gauge, LayoutDashboard, LockKeyhole, ShieldCheck, UploadCloud, XCircle, Zap } from 'lucide-react'
import useSWR from 'swr'

const fetcher = (url: string) => fetch(url).then(r => r.json())
type Stats = { total:number; low:number; medium:number; high:number; manual_reviews:number; average_score:number }
type Screen = { screening:{id:string; riskScore:number|null; riskLevel:string|null; status:string}; document:{originalFilename:string; documentType:string; fileSize:number} }

function Risk({ level }: { level:string|null }) { return <span className="inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-xs font-semibold"><span className="h-1.5 w-1.5 rounded-full bg-current"/>{level || 'PENDING'}</span> }

export default function TrustXV2() {
  const [view,setView]=useState('Overview')
  const [selected,setSelected]=useState<string|null>(null)
  const [file,setFile]=useState<File|null>(null)
  const [busy,setBusy]=useState(false)
  const [result,setResult]=useState<any>(null)
  const {data:statsResponse,mutate:refreshStats}=useSWR('/api/dashboard/stats',fetcher,{refreshInterval:15000})
  const {data:historyResponse,mutate:refreshHistory}=useSWR('/api/screenings',fetcher,{refreshInterval:10000})
  const stats:Stats|undefined=statsResponse?.data
  const history:Screen[]=historyResponse?.data || []

  async function screenDocument() {
    if (!file) return
    setBusy(true); setResult(null)
    const form = new FormData(); form.append('file',file); form.append('ownerId','00000000-0000-0000-0000-000000000001'); form.append('documentType','IDENTITY_DOCUMENT')
    try { const r=await fetch('/api/screen',{method:'POST',body:form}); const data=await r.json(); setResult(data); if(data.success){setSelected(data.data.screening.id);setView('Screening detail');await refreshStats();await refreshHistory()} } catch { setResult({success:false,error:{message:'Network error while screening document.'}}) } finally {setBusy(false)}
  }

  const nav=[['Overview',LayoutDashboard],['Screen document',UploadCloud],['Screening history',Files],['Reviews',ClipboardCheck],['Analytics',BarChart3],['Audit logs',Fingerprint]] as const
  return <div className="min-h-screen bg-[#07101d] text-slate-100">
    <aside className="fixed inset-y-0 left-0 hidden w-64 border-r border-slate-800 bg-[#091321] p-5 md:block"><div className="mb-8 flex items-center gap-3"><div className="rounded-lg bg-cyan-500/15 p-2 text-cyan-400"><ShieldCheck size={21}/></div><div><b className="tracking-widest">TRUST<span className="text-cyan-400">X</span></b><small className="block text-[9px] tracking-[.2em] text-slate-500">IDENTITY INTELLIGENCE</small></div></div><div className="mb-3 text-[10px] tracking-widest text-slate-500">WORKSPACE</div>{nav.map(([label,Icon])=><button key={label} onClick={()=>setView(label)} className={`mb-1 flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm ${view===label?'bg-cyan-500/10 text-cyan-300':'text-slate-400 hover:bg-slate-800 hover:text-white'}`}><Icon size={16}/>{label}</button>)}<div className="mt-8 border-t border-slate-800 pt-5 text-xs text-slate-500">AI detection engine <b className="float-right text-emerald-400">● Online</b></div></aside>
    <main className="md:ml-64"><header className="flex h-16 items-center justify-between border-b border-slate-800 px-5 md:px-8"><div className="text-xs text-slate-500">SECURE WORKSPACE / <span className="text-slate-300">{view.toUpperCase()}</span></div><div className="flex items-center gap-2 text-sm"><span className="h-2 w-2 rounded-full bg-emerald-400"/> All systems operational</div></header>
      <div className="mx-auto max-w-7xl p-5 md:p-8">
        {view==='Overview' && <Overview stats={stats} history={history} onNew={()=>setView('Screen document')} onOpen={(id)=>{setSelected(id);setView('Screening detail')}}/>}
        {view==='Screen document' && <Upload file={file} setFile={setFile} busy={busy} result={result} onScreen={screenDocument}/>} 
        {view==='Screening history' && <History rows={history} onOpen={(id)=>{setSelected(id);setView('Screening detail')}}/>}
        {view==='Screening detail' && <Detail id={selected} fallback={result?.data}/>} 
        {view==='Reviews' && <Reviews rows={history}/>} 
        {view==='Analytics' && <Analytics stats={stats}/>} 
        {view==='Audit logs' && <Empty title="Audit logs" text="Screening events are recorded server-side for traceability."/>}
      </div>
    </main>
  </div>
}

function Overview({stats,history,onNew,onOpen}:{stats?:Stats;history:Screen[];onNew:()=>void;onOpen:(id:string)=>void}) { return <><div className="mb-7 flex items-end justify-between gap-4"><div><div className="text-[10px] tracking-[.2em] text-cyan-400">COMMAND CENTER / OVERVIEW</div><h1 className="mt-2 text-3xl font-semibold">TrustX Operations</h1><p className="mt-1 text-sm text-slate-400">AI-assisted identity document fraud-risk screening.</p></div><button onClick={onNew} className="flex items-center gap-2 rounded-lg bg-cyan-500 px-4 py-2.5 text-sm font-semibold text-slate-950"><UploadCloud size={16}/> Start screening</button></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Documents screened',stats?.total??'—',Files],['Average risk score',stats?stats.average_score.toFixed(1):'—',Gauge],['Manual reviews',stats?.manual_reviews??'—',ClipboardCheck],['High risk',stats?.high??'—',AlertTriangle]].map(([a,b,I]:any)=><div className="rounded-xl border border-slate-800 bg-[#0b1726] p-5" key={a}><I size={18} className="mb-5 text-cyan-400"/><div className="text-xs text-slate-500">{a}</div><div className="mt-1 text-3xl font-semibold">{b}</div></div>)}</div><div className="mt-6 rounded-xl border border-slate-800 bg-[#0b1726]"><div className="border-b border-slate-800 p-5"><h2 className="font-semibold">Recent screenings</h2><p className="text-xs text-slate-500">Live records from PostgreSQL</p></div><History rows={history.slice(0,8)} onOpen={onOpen}/></div></> }

function Upload({file,setFile,busy,result,onScreen}:{file:File|null;setFile:(f:File|null)=>void;busy:boolean;result:any;onScreen:()=>void}) { return <div><div className="mb-7"><div className="text-[10px] tracking-[.2em] text-cyan-400">SECURE WORKSPACE / NEW ANALYSIS</div><h1 className="mt-2 text-3xl font-semibold">Screen document</h1><p className="mt-1 text-sm text-slate-400">Use synthetic or authorized documents only.</p></div><div className="grid gap-5 lg:grid-cols-3"><section className="rounded-xl border border-slate-800 bg-[#0b1726] p-6 lg:col-span-2"><div className="mb-5 flex justify-between"><div><h2 className="font-semibold">Upload document</h2><p className="text-xs text-slate-500">PDF, PNG or JPEG · maximum 10 MB</p></div><LockKeyhole className="text-cyan-400" size={18}/></div><label className="flex min-h-72 cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed border-slate-700 bg-slate-950/30 text-center hover:border-cyan-500/50"><input className="hidden" type="file" accept="application/pdf,image/png,image/jpeg" onChange={e=>setFile(e.target.files?.[0]||null)}/><UploadCloud size={34} className="mb-4 text-cyan-400"/>{file?<><b>{file.name}</b><span className="mt-1 text-xs text-slate-500">{(file.size/1024/1024).toFixed(2)} MB · ready</span></>:<><b>Drop document here</b><span className="mt-1 text-xs text-slate-500">or click to browse</span></>}</label><button disabled={!file||busy} onClick={onScreen} className="mt-5 flex w-full items-center justify-center gap-2 rounded-lg bg-cyan-500 py-3 font-semibold text-slate-950 disabled:cursor-not-allowed disabled:opacity-40">{busy?<><Activity className="animate-spin" size={17}/> Running screening...</>:<><Zap size={17}/> Start AI screening</>}</button>{result&&!result.success&&<div className="mt-4 rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-300">{result.error?.message}</div>}</section><section className="rounded-xl border border-slate-800 bg-[#0b1726] p-6"><h2 className="font-semibold">Analysis coverage</h2><div className="mt-5 space-y-4">{[['OCR & fields',FileSearch],['Forensic inspection',Fingerprint],['Consistency checks',ClipboardCheck],['Explainable risk',Gauge]].map(([t,I]:any)=><div className="flex items-center gap-3" key={t}><I size={17} className="text-cyan-400"/><span className="text-sm text-slate-300">{t}</span><CheckCircle2 className="ml-auto text-emerald-400" size={15}/></div>)}</div><div className="mt-6 rounded-lg border border-amber-500/20 bg-amber-500/5 p-3 text-xs leading-5 text-slate-400"><AlertTriangle size={14} className="mb-1 text-amber-400"/> Results are probabilistic and require human review.</div></section></div></div> }

function History({rows,onOpen}:{rows:Screen[];onOpen:(id:string)=>void}) { return <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-[10px] tracking-wider text-slate-500"><tr><th className="p-4">SCREENING</th><th className="p-4">DOCUMENT</th><th className="p-4">SCORE</th><th className="p-4">LEVEL</th><th className="p-4">STATUS</th><th/></tr></thead><tbody>{rows.length?rows.map(x=><tr key={x.screening.id} className="border-t border-slate-800"><td className="p-4 font-mono text-cyan-400">{x.screening.id.slice(0,8)}</td><td className="p-4"><b>{x.document.originalFilename}</b><small className="block text-slate-500">{x.document.documentType}</small></td><td className="p-4 font-semibold">{x.screening.riskScore??'—'}<small className="text-slate-500">/100</small></td><td className="p-4"><Risk level={x.screening.riskLevel}/></td><td className="p-4 text-slate-400">{x.screening.status}</td><td className="p-4"><button onClick={()=>onOpen(x.screening.id)} className="text-cyan-400">View <ChevronRight size={13} className="inline"/></button></td></tr>):<tr><td colSpan={6} className="p-10 text-center text-slate-500">No screenings yet. Upload a synthetic document to begin.</td></tr>}</tbody></table></div> }

function Detail({id,fallback}:{id:string|null;fallback:any}) { const {data}=useSWR(id?`/api/screenings/${id}`:null,fetcher); const x=data?.data||fallback; if(!x)return <Empty title="Screening detail" text="Select a screening from history."/>; const s=x.screening||x; return <div><div className="mb-7"><div className="text-[10px] tracking-[.2em] text-cyan-400">SCREENING / DETAIL</div><h1 className="mt-2 text-3xl font-semibold">Analysis report</h1></div><div className="grid gap-5 lg:grid-cols-3"><div className="rounded-xl border border-slate-800 bg-[#0b1726] p-6 lg:col-span-2"><div className="flex items-center gap-5"><div className="flex h-28 w-28 items-center justify-center rounded-full border-4 border-cyan-400/40"><b className="text-4xl">{s.riskScore??'—'}</b></div><div><div className="text-xs text-slate-500">OVERALL RISK SCORE</div><h2 className="mt-1 text-2xl font-semibold">{s.riskLevel||'Pending'}</h2><p className="text-sm text-slate-400">{s.status}</p></div></div><div className="mt-7 border-t border-slate-800 pt-5"><h3 className="font-semibold">Explainable findings</h3><div className="mt-4 space-y-3">{(x.factors||x.analysis?.factors||[]).map((f:any)=><div key={f.id||f.type} className="rounded-lg border border-slate-800 p-4"><div className="flex justify-between"><b>{f.factorType||f.type}</b><span className="text-cyan-400">{Math.round(f.score)}</span></div><p className="mt-1 text-xs text-slate-400">{f.description}</p></div>)}</div></div></div><div className="rounded-xl border border-slate-800 bg-[#0b1726] p-6"><h3 className="font-semibold">Screening metadata</h3><dl className="mt-5 space-y-4 text-sm"><div><dt className="text-slate-500">Screening ID</dt><dd className="font-mono">{s.id}</dd></div><div><dt className="text-slate-500">Model</dt><dd>{s.modelVersion||'trustx-risk-model-v1.1'}</dd></div><div><dt className="text-slate-500">OCR</dt><dd>{x.ocr?.ocrEngine||'Not available'}</dd></div><div><dt className="text-slate-500">Document</dt><dd>{x.document?.originalFilename||'—'}</dd></div></dl></div></div></div> }

function Reviews({rows}:{rows:Screen[]}) { const pending=rows.filter(x=>x.screening.status==='MANUAL_REVIEW'); return <><h1 className="mb-2 text-3xl font-semibold">Review Center</h1><p className="mb-7 text-sm text-slate-400">Cases requiring human verification.</p><div className="rounded-xl border border-slate-800 bg-[#0b1726] p-5"><div className="text-4xl font-semibold">{pending.length}</div><div className="text-xs text-slate-500">Current manual-review queue</div>{pending.length===0&&<div className="mt-6 text-sm text-slate-500">No pending cases.</div>}</div></> }
function Analytics({stats}:{stats?:Stats}) { return <><h1 className="mb-2 text-3xl font-semibold">Analytics</h1><p className="mb-7 text-sm text-slate-400">Live risk distribution from PostgreSQL.</p><div className="grid gap-4 sm:grid-cols-3">{[['LOW',stats?.low],['MEDIUM',stats?.medium],['HIGH',stats?.high]].map(([l,v])=><div className="rounded-xl border border-slate-800 bg-[#0b1726] p-6" key={l}><div className="text-xs text-slate-500">{l}</div><div className="mt-2 text-3xl font-semibold">{v??'—'}</div></div>)}</div></> }
function Empty({title,text}:{title:string;text:string}) { return <div className="rounded-xl border border-slate-800 bg-[#0b1726] p-12 text-center"><XCircle className="mx-auto mb-4 text-slate-600"/><h1 className="text-2xl font-semibold">{title}</h1><p className="mt-2 text-sm text-slate-500">{text}</p></div> }
